---
- name: Set tmp file name
  set_fact:
    tmpFileName: "/tmp/openssl-{{ cert_config.cn }}.conf"

- name: Save the openssl config file
  template:
    src: templates/openssl.conf.j2
    dest: "/tmp/openssl-{{ cert_config.cn }}.conf"
  delegate_to: localhost

- command: which openssl

- name: Set args
  set_fact:
    openssl_args: "req -sha256 -nodes -config /tmp/openssl-{{ cert_config.cn }}.conf -newkey rsa:{{ keygen.bits }} -out '{{ cert_path.csr }}' -keyout '{{ cert_path.key.local }}' "

- name: Ensure local path exists
  file:
    path: "{{ base_paths.local }}"
    state: directory
    recurse: yes
  delegate_to: localhost

- name: Creating CSR and RSA key
  command: openssl {{ openssl_args }}
  delegate_to: localhost
  when: true
